environment:
  matrix:
    nodejs_version: "4"
    nodejs_version: "5"
    nodejs_version: "6"
    nodejs_version: "7"

branches:
  only:
  - master

skip_tags: true

max_jobs: 4

clone_depth: 50

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - cmd: gcov

build: off

deploy: off
